database: hsqldb

spring:
  datasource:
    schema: "classpath:db/${database}/schema.sql"
    data: "classpath:db/${database}/data.sql"
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false