spring:
  application:
    name: mybatis-master-slave
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8080

logging:
  level:
    com.yunus.mapper: debug