server:
  port: 8080

spring:
  application:
    name: spring-security-oauth2


security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234
      registered-redirect-uri: http://www.baidu.com