version: "2.2"
services:
  elasticsearch:
    image: elasticsearch:6.8.1
    container_name: es-server
    environment:
      - cluster.name=es-single
      - node.name=es-data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
    image: kibana:6.8.1
    container_name: kibana-server
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - esnet
networks:
  esnet:
    driver: bridge
