version: "3.3"

services:
  hello-world-admin:
    # 指定构建Dockerfile 目录
    build: ./
    # 镜像名称
    image: hello-world:1.0
    # 容器名称
    container_name: hello-world-admin
    # 指定网络
    networks:
      - ng-network

  hello-world-api:
    build: ./
    image: hello-world:1.0
    container_name: hello-world-api
    networks:
      - ng-network

  nginx-server:
    image: nginx
    container_name: nginx-server
    volumes:
      # nginx.conf 文件内容和 同目录下的nginx.conf 内容一样 做代理admin 和 api 服务
      - /Users/gaoyunfeng/Applications/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - ng-network
networks:
  ng-network:
    external: true