server:
  port: 8080
spring:
  application:
    name: security-three
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
